version = 1

[[migrations]]
id = 7364140792646974194
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 712091361848085153
name = "0001_migration.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 1042174621825372039
name = "0002_migration.sql"
snapshot_name = "0002_snapshot.toml"
