[package]
name = "propagation-web"
version.workspace = true
edition.workspace = true

[dependencies]
geojson.workspace = true
jiff.workspace = true
libpropagation.workspace = true
serde.workspace = true
serde_urlencoded = "0.7.1"
serde_json.workspace = true
thiserror.workspace = true
toasty.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
topcoat = { version = "0.5.0", features = ["font-fontsource", "icon-iconify", "tailwind"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
topcoat = { version = "0.5.0", default-features= false, features = ["tailwind", "icon-iconify"] }
